// Code generated by registry/generate_init.go; DO NOT EDIT
package registry

import (
	"github.com/panther-labs/panther/internal/log_analysis/log_processor/logtypes"
	// Packages that export log types

	apachelogs "github.com/panther-labs/panther/internal/log_analysis/log_processor/parsers/apachelogs"

	awslogs "github.com/panther-labs/panther/internal/log_analysis/log_processor/parsers/awslogs"

	boxlogs "github.com/panther-labs/panther/internal/log_analysis/log_processor/parsers/boxlogs"

	cloudflarelogs "github.com/panther-labs/panther/internal/log_analysis/log_processor/parsers/cloudflarelogs"

	crowdstrikelogs "github.com/panther-labs/panther/internal/log_analysis/log_processor/parsers/crowdstrikelogs"

	duologs "github.com/panther-labs/panther/internal/log_analysis/log_processor/parsers/duologs"

	fastlylogs "github.com/panther-labs/panther/internal/log_analysis/log_processor/parsers/fastlylogs"

	fluentdsyslogs "github.com/panther-labs/panther/internal/log_analysis/log_processor/parsers/fluentdsyslogs"

	gcplogs "github.com/panther-labs/panther/internal/log_analysis/log_processor/parsers/gcplogs"

	gitlablogs "github.com/panther-labs/panther/internal/log_analysis/log_processor/parsers/gitlablogs"

	gravitationallogs "github.com/panther-labs/panther/internal/log_analysis/log_processor/parsers/gravitationallogs"

	gsuitelogs "github.com/panther-labs/panther/internal/log_analysis/log_processor/parsers/gsuitelogs"

	juniperlogs "github.com/panther-labs/panther/internal/log_analysis/log_processor/parsers/juniperlogs"

	laceworklogs "github.com/panther-labs/panther/internal/log_analysis/log_processor/parsers/laceworklogs"

	nginxlogs "github.com/panther-labs/panther/internal/log_analysis/log_processor/parsers/nginxlogs"

	oktalogs "github.com/panther-labs/panther/internal/log_analysis/log_processor/parsers/oktalogs"

	oneloginlogs "github.com/panther-labs/panther/internal/log_analysis/log_processor/parsers/oneloginlogs"

	osquerylogs "github.com/panther-labs/panther/internal/log_analysis/log_processor/parsers/osquerylogs"

	osseclogs "github.com/panther-labs/panther/internal/log_analysis/log_processor/parsers/osseclogs"

	slacklogs "github.com/panther-labs/panther/internal/log_analysis/log_processor/parsers/slacklogs"

	sophoslogs "github.com/panther-labs/panther/internal/log_analysis/log_processor/parsers/sophoslogs"

	suricatalogs "github.com/panther-labs/panther/internal/log_analysis/log_processor/parsers/suricatalogs"

	sysloglogs "github.com/panther-labs/panther/internal/log_analysis/log_processor/parsers/sysloglogs"

	umbrellalogs "github.com/panther-labs/panther/internal/log_analysis/log_processor/parsers/umbrellalogs"

	zeeklogs "github.com/panther-labs/panther/internal/log_analysis/log_processor/parsers/zeeklogs"
)

func init() {
	// Initialize the registered log types group
	nativeLogTypes = logtypes.MustMerge("registered",

		apachelogs.LogTypes(),

		awslogs.LogTypes(),

		boxlogs.LogTypes(),

		cloudflarelogs.LogTypes(),

		crowdstrikelogs.LogTypes(),

		duologs.LogTypes(),

		fastlylogs.LogTypes(),

		fluentdsyslogs.LogTypes(),

		gcplogs.LogTypes(),

		gitlablogs.LogTypes(),

		gravitationallogs.LogTypes(),

		gsuitelogs.LogTypes(),

		juniperlogs.LogTypes(),

		laceworklogs.LogTypes(),

		nginxlogs.LogTypes(),

		oktalogs.LogTypes(),

		oneloginlogs.LogTypes(),

		osquerylogs.LogTypes(),

		osseclogs.LogTypes(),

		slacklogs.LogTypes(),

		sophoslogs.LogTypes(),

		suricatalogs.LogTypes(),

		sysloglogs.LogTypes(),

		umbrellalogs.LogTypes(),

		zeeklogs.LogTypes(),
	)
}
